name: CLA Signature
description: Template for issues triggering CLA signature
title: CLA signature
labels:
  - cla-signing
body:
  - type: markdown
    attributes:
      value: |
        Submitting this issue will add you to the list of rxn4chemistry contributors.
  - type: checkboxes
    id: cla
    attributes:
      label: Contributor License Agreement
      options:
        - label: I accept and sign the contributor license agreement ([CLA](https://github.com/rxn4chemistry/clabot-config/blob/main/CONTRIBUTING.md#contributor-license-agreement)) to contribute to rxn4chemistry.
          required: true
